package openai

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// codexModelEntry mirrors the relevant fields of a model entry in
// ~/.codex/models_cache.json.
type codexModelEntry struct {
	Slug                     string                `json:"slug"`
	DisplayName              string                `json:"display_name"`
	Description              string                `json:"description"`
	ContextWindow            uint64                `json:"context_window"`
	DefaultReasoningLevel    string                `json:"default_reasoning_level"`
	Visibility               string                `json:"visibility"`
	SupportedInAPI           bool                  `json:"supported_in_api"`
	SupportedReasoningLevels []codexReasoningLevel `json:"supported_reasoning_levels"`
}

type codexModelsCache struct {
	ETag   string            `json:"etag"`
	Models []codexModelEntry `json:"models"`
}

type codexReasoningLevel struct {
	Effort      string `json:"effort"`
	Description string `json:"description"`
}

// lookupCodexContextWindow returns the positive context window advertised for a
// model slug in the Codex model cache.
func lookupCodexContextWindow(cache codexModelsCache, slug string) (uint64, error) {
	for _, model := range cache.Models {
		if model.Slug != slug {
			continue
		}
		if model.ContextWindow == 0 {
			return 0, fmt.Errorf("model %q has no positive context_window in the Codex model cache", slug)
		}
		return model.ContextWindow, nil
	}
	return 0, fmt.Errorf("model %q was not found in the Codex model cache", slug)
}

func readCodexContextWindow(path string, slug string) (uint64, error) {
	cache, err := readCodexModelsCache(path)
	if err != nil {
		return 0, err
	}
	return lookupCodexContextWindow(cache, slug)
}

// handleCodexModels reads ~/.codex/models_cache.json and prints
// ready-to-paste [model.*] blocks for ~/.grok/config.toml, one per
// model × effort combination. The effort is encoded in both the
// section name and the model field (e.g. "gpt-5.6-luna:high") so the
// proxy can parse and inject it upstream.
func handleCodexModels(args []string) error {
	path := codexModelsCachePath()
	cache, err := readCodexModelsCache(path)
	if err != nil {
		return err
	}

	output, err := generateCodexModelsConfig(cache, "http://localhost:8891/v1")
	if err != nil {
		return err
	}
	fmt.Print(output)
	return nil
}

func generateCodexModelsConfig(cache codexModelsCache, endpoint string) (string, error) {
	var output strings.Builder
	fmt.Fprintf(&output, "# Paste into ~/.grok/config.toml\n")
	fmt.Fprintf(&output, "# Generated by: llm-proxy codex-models\n")
	fmt.Fprintf(&output, "# Endpoint: %s\n", endpoint)
	fmt.Fprintf(&output, "# Reasoning effort is encoded in both the section name and model field\n\n")
	for _, m := range cache.Models {
		if m.Visibility != "list" || !m.SupportedInAPI {
			continue
		}
		contextWindow, err := lookupCodexContextWindow(cache, m.Slug)
		if err != nil {
			return "", fmt.Errorf("cannot generate config for %q: %w", m.Slug, err)
		}
		levels := m.SupportedReasoningLevels
		if len(levels) == 0 {
			levels = []codexReasoningLevel{{Effort: m.DefaultReasoningLevel}}
		}
		isDefault := func(effort string) bool {
			return effort == m.DefaultReasoningLevel
		}
		for _, lvl := range levels {
			section := slugToSection(m.Slug, lvl.Effort)
			modelField := m.Slug + ":" + lvl.Effort
			name := m.DisplayName + " (" + lvl.Effort + ")"
			fmt.Fprintf(&output, "[model.\"%s\"]\n", section)
			fmt.Fprintf(&output, "model = \"%s\"\n", modelField)
			fmt.Fprintf(&output, "base_url = \"%s\"\n", endpoint)
			fmt.Fprintf(&output, "name = \"%s\"\n", name)
			fmt.Fprintf(&output, "api_backend = \"responses\"\n")
			fmt.Fprintf(&output, "context_window = %d", contextWindow)
			if isDefault(lvl.Effort) {
				fmt.Fprintf(&output, "  # default effort")
			}
			fmt.Fprintf(&output, "\n\n")
		}
	}
	return output.String(), nil
}

func readCodexModelsCache(path string) (codexModelsCache, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return codexModelsCache{}, fmt.Errorf("cannot read %s: %w\nrun `codex login` to populate the cache", path, err)
	}
	var cache codexModelsCache
	if err := json.Unmarshal(data, &cache); err != nil {
		return codexModelsCache{}, fmt.Errorf("invalid models cache %s: %w", path, err)
	}
	return cache, nil
}

// slugToSection converts a model slug like "gpt-5.6-luna" and an
// effort like "high" to a TOML key "codex-5.6-luna-high". The "gpt-"
// prefix is stripped and the effort is appended after a dash.
func slugToSection(slug string, effort string) string {
	s := strings.TrimPrefix(slug, "gpt-")
	return "codex-" + s + "-" + effort
}

// codexModelsCachePath returns the path to ~/.codex/models_cache.json.
func codexModelsCachePath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".codex", "models_cache.json")
}
