package openai

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// codexModelEntry mirrors the relevant fields of a model entry in
// ~/.codex/models_cache.json.
type codexModelEntry struct {
	Slug                     string                `json:"slug"`
	DisplayName              string                `json:"display_name"`
	Description              string                `json:"description"`
	ContextWindow            uint64                `json:"context_window"`
	DefaultReasoningLevel    string                `json:"default_reasoning_level"`
	Visibility               string                `json:"visibility"`
	SupportedInAPI           bool                  `json:"supported_in_api"`
	SupportedReasoningLevels []codexReasoningLevel `json:"supported_reasoning_levels"`
}

type codexModelsCache struct {
	ETag   string            `json:"etag"`
	Models []codexModelEntry `json:"models"`
}

type codexReasoningLevel struct {
	Effort      string `json:"effort"`
	Description string `json:"description"`
}

// handleCodexModels reads ~/.codex/models_cache.json and prints
// ready-to-paste [model.*] blocks for ~/.grok/config.toml, one per
// model × effort combination. The effort is encoded in both the
// section name and the model field (e.g. "gpt-5.6-luna:high") so the
// proxy can parse and inject it upstream.
func handleCodexModels(args []string) error {
	path := codexModelsCachePath()
	cache, err := readCodexModelsCache(path)
	if err != nil {
		return err
	}

	endpoint := "http://localhost:8891/v1"
	fmt.Printf("# Paste into ~/.grok/config.toml\n")
	fmt.Printf("# Generated by: llm-proxy codex-models\n")
	fmt.Printf("# Endpoint: %s\n", endpoint)
	fmt.Printf("# Reasoning effort is encoded in both the section name and model field\n\n")
	for _, m := range cache.Models {
		if m.Visibility != "list" || !m.SupportedInAPI {
			continue
		}
		levels := m.SupportedReasoningLevels
		if len(levels) == 0 {
			levels = []codexReasoningLevel{{Effort: m.DefaultReasoningLevel}}
		}
		isDefault := func(effort string) bool {
			return effort == m.DefaultReasoningLevel
		}
		for _, lvl := range levels {
			section := slugToSection(m.Slug, lvl.Effort)
			modelField := m.Slug + ":" + lvl.Effort
			name := m.DisplayName + " (" + lvl.Effort + ")"
			fmt.Printf("[model.\"%s\"]\n", section)
			fmt.Printf("model = \"%s\"\n", modelField)
			fmt.Printf("base_url = \"%s\"\n", endpoint)
			fmt.Printf("name = \"%s\"\n", name)
			fmt.Printf("api_backend = \"responses\"\n")
			fmt.Printf("context_window = 200000")
			if isDefault(lvl.Effort) {
				fmt.Printf("  # default effort")
			}
			fmt.Printf("\n\n")
		}
	}
	return nil
}

func readCodexModelsCache(path string) (codexModelsCache, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return codexModelsCache{}, fmt.Errorf("cannot read %s: %w\nrun `codex login` to populate the cache", path, err)
	}
	var cache codexModelsCache
	if err := json.Unmarshal(data, &cache); err != nil {
		return codexModelsCache{}, fmt.Errorf("invalid models cache %s: %w", path, err)
	}
	return cache, nil
}

// slugToSection converts a model slug like "gpt-5.6-luna" and an
// effort like "high" to a TOML key "codex-5.6-luna-high". The "gpt-"
// prefix is stripped and the effort is appended after a dash.
func slugToSection(slug string, effort string) string {
	s := strings.TrimPrefix(slug, "gpt-")
	return "codex-" + s + "-" + effort
}

// codexModelsCachePath returns the path to ~/.codex/models_cache.json.
func codexModelsCachePath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".codex", "models_cache.json")
}
