package openai

import (
	"fmt"
	"sort"
	"strings"

	"github.com/xhd2015/less-gen/flags"
)

const configModelsHelp = `
Usage: llm-proxy --config FILE {codex-models|grok-models|dsh-models}

Print model configuration selected for the named agent runner.

Options:
  -h, --help    show this help
`

func handleConfigModels(path, command string, args []string) error {
	args, err := flags.Help("-h,--help", configModelsHelp).Parse(args)
	if err != nil {
		return err
	}
	if len(args) > 0 {
		return fmt.Errorf("unrecognized extra args: %s", strings.Join(args, " "))
	}
	config, routes, err := loadProxyConfig(path)
	if err != nil {
		return fmt.Errorf("load --config: %w", err)
	}
	runner := strings.TrimSuffix(command, "-models")
	endpoint := "http://" + config.Listen + "/v1"
	routes = routesForAgentRunner(routes, runner)
	routes = withoutRunnerProvider(routes, runner)
	switch runner {
	case "codex":
		fmt.Print(generateConfigCodexModels(endpoint, routes))
	case "grok":
		fmt.Print(generateConfigGrokModels(endpoint, routes))
	case "dsh":
		fmt.Print(generateConfigDSHModels(config.Listen, routes))
	default:
		return fmt.Errorf("unsupported agent runner %q", runner)
	}
	return nil
}

func withoutRunnerProvider(routes []effectiveRoute, runner string) []effectiveRoute {
	filtered := make([]effectiveRoute, 0, len(routes))
	for _, route := range routes {
		if route.provider.Kind != runner {
			filtered = append(filtered, route)
		}
	}
	return filtered
}

func generateConfigCodexModels(endpoint string, routes []effectiveRoute) string {
	responses := routesForProtocol(routes, "openai-responses")
	var out strings.Builder
	fmt.Fprintln(&out, "# Paste into ~/.codex/config.toml")
	fmt.Fprintln(&out, "# Generated by: llm-proxy --config FILE codex-models")
	fmt.Fprintf(&out, "# Endpoint: %s\n", endpoint)
	if len(responses) == 0 {
		fmt.Fprintln(&out, "# No OpenAI Responses models are configured for Codex.")
		return out.String()
	}
	fmt.Fprintln(&out, "# Models:")
	for _, route := range responses {
		fmt.Fprintf(&out, "#   %s\n", route.clientModelName)
	}
	fmt.Fprintf(&out, "\nmodel = %q\n", responses[0].clientModelName)
	fmt.Fprintln(&out, "model_provider = \"llm-proxy\"")
	fmt.Fprintln(&out, "")
	fmt.Fprintln(&out, "[model_providers.llm-proxy]")
	fmt.Fprintln(&out, "name = \"LLM Proxy\"")
	fmt.Fprintf(&out, "base_url = %q\n", endpoint)
	fmt.Fprintln(&out, "wire_api = \"responses\"")
	return out.String()
}

func generateConfigGrokModels(endpoint string, routes []effectiveRoute) string {
	var out strings.Builder
	fmt.Fprintln(&out, "# Paste into ~/.grok/config.toml")
	fmt.Fprintln(&out, "# Generated by: llm-proxy --config FILE grok-models")
	fmt.Fprintf(&out, "# Endpoint: %s\n\n", endpoint)
	if len(routes) == 0 {
		fmt.Fprintln(&out, "# No external routes are configured for Grok.")
		return out.String()
	}
	for _, route := range sortRoutes(routes) {
		backend := "responses"
		if route.protocol == "anthropic-messages" {
			backend = "messages"
		}
		fmt.Fprintf(&out, "[model.%q]\n", route.clientModelName)
		fmt.Fprintf(&out, "model = %q\n", route.clientModelName)
		fmt.Fprintf(&out, "base_url = %q\n", endpoint)
		fmt.Fprintf(&out, "name = %q\n", route.clientModelName)
		fmt.Fprintf(&out, "api_backend = %q\n\n", backend)
	}
	return out.String()
}

func generateConfigDSHModels(listen string, routes []effectiveRoute) string {
	messages := routesForProtocol(routes, "anthropic-messages")
	responses := routesForProtocol(routes, "openai-responses")
	base := "http://" + strings.Replace(listen, "localhost", "127.0.0.1", 1)
	var out strings.Builder
	if len(routes) == 0 {
		fmt.Fprintln(&out, "# No external routes are configured for Deepseek Harness.")
		return out.String()
	}
	fmt.Fprintln(&out, "llm-pi-ai:")
	fmt.Fprintln(&out, "  providers:")
	writeDSHProvider(&out, "llm-proxy-messages", "Anthropic Messages", "anthropic-messages", base, messages)
	writeDSHProvider(&out, "llm-proxy-responses", "OpenAI Responses", "openai-responses", base+"/v1", responses)
	return out.String()
}

func writeDSHProvider(out *strings.Builder, name, displayName, api, baseURL string, routes []effectiveRoute) {
	if len(routes) == 0 {
		return
	}
	fmt.Fprintf(out, "    %s:\n", name)
	fmt.Fprintf(out, "      displayName: %s (llm-proxy)\n", displayName)
	fmt.Fprintf(out, "      api: %s\n", api)
	fmt.Fprintf(out, "      baseURL: %s\n", baseURL)
	fmt.Fprintln(out, "      models:")
	for _, route := range routes {
		name := route.displayName
		if name == "" {
			name = route.clientModelName
		}
		fmt.Fprintf(out, "        - id: %s\n", route.clientModelName)
		fmt.Fprintf(out, "          name: %s\n", name)
		if len(route.input) > 0 {
			fmt.Fprintf(out, "          input: [ %s ]\n", strings.Join(route.input, ", "))
		}
		if route.contextWindow != nil {
			fmt.Fprintf(out, "          contextWindow: %d\n", *route.contextWindow)
		}
		if route.maxTokens != nil {
			fmt.Fprintf(out, "          maxTokens: %d\n", *route.maxTokens)
		}
		writeDSHCompat(out, route.compat)
		writeDSHReasoningEfforts(out, route.reasoningEfforts)
	}
}

func writeDSHCompat(out *strings.Builder, compat map[string]bool) {
	if len(compat) == 0 {
		return
	}
	fmt.Fprintln(out, "          compat:")
	keys := make([]string, 0, len(compat))
	for key := range compat {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(out, "            %s: %t\n", key, compat[key])
	}
}

func writeDSHReasoningEfforts(out *strings.Builder, efforts map[string]*string) {
	if len(efforts) == 0 {
		return
	}
	fmt.Fprintln(out, "          reasoningEfforts:")
	keys := make([]string, 0, len(efforts))
	for key := range efforts {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := efforts[key]
		if value == nil {
			fmt.Fprintf(out, "            %s:\n", key)
			continue
		}
		fmt.Fprintf(out, "            %s: %s\n", key, *value)
	}
}

func routesForProtocol(routes []effectiveRoute, protocol string) []effectiveRoute {
	filtered := make([]effectiveRoute, 0, len(routes))
	for _, route := range routes {
		if route.protocol == protocol {
			filtered = append(filtered, route)
		}
	}
	return sortRoutes(filtered)
}

func sortRoutes(routes []effectiveRoute) []effectiveRoute {
	sorted := append([]effectiveRoute(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].clientModelName < sorted[j].clientModelName })
	return sorted
}
