package openai

import (
	"fmt"
	"sort"
	"strings"

	"github.com/xhd2015/less-gen/flags"
)

const configModelsHelp = `
Usage: llm-proxy --config FILE {codex-models|grok-models|dsh-models}
       llm-proxy dsh-models --config FILE

Print model configuration selected for the named agent runner.

Options:
  --config FILE  read configured model routes
  -h, --help    show this help
`

func handleConfigModels(path, command string, args []string) error {
	args, err := flags.String("--config", &path).Help("-h,--help", configModelsHelp).Parse(args)
	if err != nil {
		return err
	}
	if len(args) > 0 {
		return fmt.Errorf("unrecognized extra args: %s", strings.Join(args, " "))
	}
	if path == "" {
		return fmt.Errorf("%s requires --config FILE", command)
	}
	config, routes, err := loadProxyConfig(path)
	if err != nil {
		return fmt.Errorf("load --config: %w", err)
	}
	runner := strings.TrimSuffix(command, "-models")
	output, err := generateConfigModels(config.Listen, routes, runner)
	if err != nil {
		return err
	}
	fmt.Print(output)
	return nil
}

func generateConfigModels(listen string, routes []effectiveRoute, runner string) (string, error) {
	endpoint := "http://" + listen + "/v1"
	routes = routesForAgentRunner(routes, runner)
	routes = withoutRunnerProvider(routes, runner)
	switch runner {
	case "codex":
		return generateConfigCodexModels(endpoint, routes), nil
	case "grok":
		return generateConfigGrokModels(endpoint, routes), nil
	case "dsh":
		return generateConfigDSHModels(listen, routes)
	default:
		return "", fmt.Errorf("unsupported agent runner %q", runner)
	}
}

func withoutRunnerProvider(routes []effectiveRoute, runner string) []effectiveRoute {
	filtered := make([]effectiveRoute, 0, len(routes))
	for _, route := range routes {
		if route.provider.Kind != runner {
			filtered = append(filtered, route)
		}
	}
	return filtered
}

func generateConfigCodexModels(endpoint string, routes []effectiveRoute) string {
	responses := routesForProtocol(routes, "openai-responses")
	var out strings.Builder
	fmt.Fprintln(&out, "# Paste into ~/.codex/config.toml")
	fmt.Fprintln(&out, "# Generated by: llm-proxy --config FILE codex-models")
	fmt.Fprintf(&out, "# Endpoint: %s\n", endpoint)
	if len(responses) == 0 {
		fmt.Fprintln(&out, "# No OpenAI Responses models are configured for Codex.")
		return out.String()
	}
	fmt.Fprintln(&out, "# Models:")
	for _, route := range responses {
		fmt.Fprintf(&out, "#   %s\n", route.clientModelName)
	}
	fmt.Fprintf(&out, "\nmodel = %q\n", responses[0].clientModelName)
	fmt.Fprintln(&out, "model_provider = \"llm-proxy\"")
	fmt.Fprintln(&out, "")
	fmt.Fprintln(&out, "[model_providers.llm-proxy]")
	fmt.Fprintln(&out, "name = \"LLM Proxy\"")
	fmt.Fprintf(&out, "base_url = %q\n", endpoint)
	fmt.Fprintln(&out, "wire_api = \"responses\"")
	return out.String()
}

func generateConfigGrokModels(endpoint string, routes []effectiveRoute) string {
	var out strings.Builder
	fmt.Fprintln(&out, "# Paste into ~/.grok/config.toml")
	fmt.Fprintln(&out, "# Generated by: llm-proxy --config FILE grok-models")
	fmt.Fprintf(&out, "# Endpoint: %s\n\n", endpoint)
	if len(routes) == 0 {
		fmt.Fprintln(&out, "# No external routes are configured for Grok.")
		return out.String()
	}
	for _, route := range sortRoutes(routes) {
		backend := "responses"
		if route.protocol == "anthropic-messages" {
			backend = "messages"
		}
		fmt.Fprintf(&out, "[model.%q]\n", route.clientModelName)
		fmt.Fprintf(&out, "model = %q\n", route.clientModelName)
		fmt.Fprintf(&out, "base_url = %q\n", endpoint)
		fmt.Fprintf(&out, "name = %q\n", route.clientModelName)
		fmt.Fprintf(&out, "api_backend = %q\n\n", backend)
	}
	return out.String()
}

type dshProviderGroup struct {
	name      string
	display   string
	protocol  string
	reasoning string
	routes    []effectiveRoute
}

func generateConfigDSHModels(listen string, routes []effectiveRoute) (string, error) {
	if len(routes) == 0 {
		return "# No external routes are configured for Deepseek Harness.\n", nil
	}
	for _, route := range routes {
		if len(route.input) == 0 {
			return "", fmt.Errorf("model %q: DSH export requires at least one enabled input", route.clientModelName)
		}
	}
	groups := groupDSHRoutes(routes)
	seen := make(map[string]bool)
	for _, group := range groups {
		if seen[group.name] {
			return "", fmt.Errorf("DSH provider name %q collides; rename the configured provider", group.name)
		}
		seen[group.name] = true
	}
	base := "http://" + strings.Replace(listen, "localhost", "127.0.0.1", 1)
	var out strings.Builder
	fmt.Fprintln(&out, "# Store a non-empty placeholder for each apiKeyEnv in DSH credentials or the environment.")
	fmt.Fprintln(&out, "llm-proxy-providers:")
	fmt.Fprintln(&out, "  providers:")
	for _, group := range groups {
		baseURL := base
		if group.protocol == "openai-responses" {
			baseURL += "/v1"
		}
		writeDSHProvider(&out, group, baseURL)
	}
	return out.String(), nil
}

func groupDSHRoutes(routes []effectiveRoute) []dshProviderGroup {
	groupsByKey := make(map[string]*dshProviderGroup)
	providerProtocolCounts := make(map[string]int)
	for _, route := range routes {
		key := route.provider.Name + "\x00" + route.protocol
		group := groupsByKey[key]
		if group == nil {
			group = &dshProviderGroup{display: dshProviderDisplayName(route.provider), protocol: route.protocol}
			groupsByKey[key] = group
			providerProtocolCounts[route.provider.Name]++
		}
		group.routes = append(group.routes, route)
	}
	groups := make([]dshProviderGroup, 0, len(groupsByKey))
	for key, group := range groupsByKey {
		parts := strings.Split(key, "\x00")
		group.name = "llm-proxy-" + parts[0]
		if providerProtocolCounts[parts[0]] > 1 {
			backend := parts[1]
			group.name += "-" + backend
		}
		group.reasoning = sharedDSHReasoning(group.routes)
		group.routes = sortRoutes(group.routes)
		groups = append(groups, *group)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].name < groups[j].name })
	return groups
}

func sharedDSHReasoning(routes []effectiveRoute) string {
	if len(routes) == 0 {
		return ""
	}
	allDisabled := true
	sawDisabled := false
	var shared string
	for _, route := range routes {
		if route.reasoning.Disabled {
			sawDisabled = true
			if shared != "" {
				return ""
			}
			continue
		}
		if sawDisabled {
			return ""
		}
		allDisabled = false
		if shared == "" {
			shared = route.reasoning.DefaultEffort
			continue
		}
		if shared != route.reasoning.DefaultEffort {
			return ""
		}
	}
	if allDisabled {
		return "off"
	}
	return shared
}

func dshProviderDisplayName(provider configProvider) string {
	switch provider.Kind {
	case "commandcode":
		return "Command Code"
	case "codex":
		return "Codex"
	case "grok":
		return "Grok"
	case "http-proxy":
		return strings.ToUpper(provider.Name)
	default:
		return provider.Name
	}
}

func writeDSHProvider(out *strings.Builder, group dshProviderGroup, baseURL string) {
	fmt.Fprintf(out, "    %s:\n", group.name)
	fmt.Fprintf(out, "      displayName: %s (llm-proxy)\n", group.display)
	credential := strings.Map(func(r rune) rune {
		if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			return r
		}
		return '_'
	}, strings.ToUpper(group.routes[0].provider.Name)) + "_API_KEY"
	if credential[0] >= '0' && credential[0] <= '9' {
		credential = "LLM_PROXY_" + credential
	}
	fmt.Fprintf(out, "      apiKeyEnv: %s\n", credential)
	fmt.Fprintf(out, "      api: %s\n", group.protocol)
	fmt.Fprintf(out, "      baseURL: %s\n", baseURL)
	if group.reasoning != "" {
		fmt.Fprintf(out, "      reasoning: %q\n", group.reasoning)
	}
	fmt.Fprintln(out, "      models:")
	for _, route := range group.routes {
		name := route.displayName
		if name == "" {
			name = route.clientModelName
		}
		fmt.Fprintf(out, "        - id: %s\n", route.clientModelName)
		fmt.Fprintf(out, "          name: %s\n", name)
		if len(route.input) > 0 {
			fmt.Fprintf(out, "          input: [ %s ]\n", strings.Join(route.input, ", "))
		}
		if route.contextWindow != nil {
			fmt.Fprintf(out, "          contextWindow: %d\n", *route.contextWindow)
		}
		if route.maxTokens != nil {
			fmt.Fprintf(out, "          maxTokens: %d\n", *route.maxTokens)
		}
		writeDSHCompat(out, route.compat)
		if !route.reasoning.Disabled {
			writeDSHReasoningEfforts(out, route.reasoning.EffortsMapping)
		}
	}
}

func writeDSHCompat(out *strings.Builder, compat map[string]bool) {
	if len(compat) == 0 {
		return
	}
	fmt.Fprintln(out, "          compat:")
	keys := make([]string, 0, len(compat))
	for key := range compat {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(out, "            %s: %t\n", key, compat[key])
	}
}

func writeDSHReasoningEfforts(out *strings.Builder, efforts map[string]*string) {
	if len(efforts) == 0 {
		return
	}
	fmt.Fprintln(out, "          reasoningEfforts:")
	keys := make([]string, 0, len(efforts))
	for key := range efforts {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := efforts[key]
		if value == nil {
			fmt.Fprintf(out, "            %s:\n", key)
			continue
		}
		fmt.Fprintf(out, "            %s: %s\n", key, *value)
	}
}

func routesForProtocol(routes []effectiveRoute, protocol string) []effectiveRoute {
	filtered := make([]effectiveRoute, 0, len(routes))
	for _, route := range routes {
		if route.protocol == protocol {
			filtered = append(filtered, route)
		}
	}
	return sortRoutes(filtered)
}

func sortRoutes(routes []effectiveRoute) []effectiveRoute {
	sorted := append([]effectiveRoute(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].clientModelName < sorted[j].clientModelName })
	return sorted
}
