package commandcode

import (
	"fmt"
	"strings"
)

// apiBackend is the Grok CLI API backend this proxy implements. Command Code's
// wire format uses Anthropic-shaped content blocks and input_schema tools, so
// the Anthropic Messages backend is the closest match.
const apiBackend = "messages"

// modelsV2Response is the Grok CLI model-catalog payload (GET /v1/models-v2).
type modelsV2Response struct {
	Data []modelsV2Entry `json:"data"`
}

type modelsV2Entry struct {
	ID            string `json:"id"`
	Model         string `json:"model"`
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	ContextWindow uint64 `json:"context_window,omitempty"`
	BaseURL       string `json:"base_url"`
	APIBackend    string `json:"api_backend"`
}

// ModelsV2 builds the Grok CLI catalog. Grok requests this on resume from idle
// to refresh context-window metadata.
func ModelsV2(endpoint string) modelsV2Response {
	response := modelsV2Response{Data: make([]modelsV2Entry, 0, len(Catalog))}
	for _, m := range Catalog {
		response.Data = append(response.Data, modelsV2Entry{
			ID:            m.ID,
			Model:         m.ID,
			Name:          displayName(m),
			Description:   m.Description,
			ContextWindow: m.ContextWindow,
			BaseURL:       endpoint,
			APIBackend:    apiBackend,
		})
	}
	return response
}

// ConfigBlocks renders ready-to-paste [model.*] blocks for ~/.grok/config.toml,
// mirroring `llm-proxy codex-models`.
func ConfigBlocks(endpoint string) string {
	var out strings.Builder
	fmt.Fprintf(&out, "# Paste into ~/.grok/config.toml\n")
	fmt.Fprintf(&out, "# Generated by: llm-proxy commandcode-models\n")
	fmt.Fprintf(&out, "# Endpoint: %s\n", endpoint)
	fmt.Fprintf(&out, "# %d Command Code models; plan gating still applies server-side\n\n", len(Catalog))

	for _, m := range Catalog {
		fmt.Fprintf(&out, "[model.\"%s\"]\n", SectionName(m.ID))
		fmt.Fprintf(&out, "model = \"%s\"\n", m.ID)
		fmt.Fprintf(&out, "base_url = \"%s\"\n", endpoint)
		fmt.Fprintf(&out, "name = \"%s\"\n", displayName(m))
		fmt.Fprintf(&out, "api_backend = \"%s\"\n", apiBackend)
		if m.ContextWindow > 0 {
			fmt.Fprintf(&out, "context_window = %d\n", m.ContextWindow)
		}
		fmt.Fprintf(&out, "\n")
	}
	return out.String()
}

// SectionName is the [model."<section>"] key for a Command Code model id.
func SectionName(id string) string {
	short := id
	if i := strings.LastIndex(id, "/"); i >= 0 {
		short = id[i+1:]
	}
	return "cc-" + short
}

func displayName(m Model) string {
	name := m.Name
	if name == "" {
		name = m.ID
	}
	return name + " (Command Code)"
}
